format = """
[](fg:#4d576a)\
$directory\
[](fg:#4d576a bg:#5f6f86)\
$git_branch\
$git_status\
[](fg:#5f6f86 bg:#7087a3)\
$c\
$dotnet\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$python\
[](fg:#7087a3 bg:#81a1c1)\
$status\
[](fg:#81a1c1)\
"""

right_format = "$cmd_duration"
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[os.symbols]
Arch = " "
# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[directory]
style = "bg:#4d576a"
format = "[ $path ]($style)"
truncation_length=1
fish_style_pwd_dir_length=3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
# "Documents" = "󰈙"
# "Downloads" = ""
# "Music" = ""
# "Pictures" = ""
# # Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "



[c]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style)'

[dotnet]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'
version_format = 'v${major}.${minor}'

[elixir]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#5f6f86"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#5f6f86"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "  "
style = "bg:#7087a3"
format = '[ $symbol ($version) ]($style)'

[status]
style = "bg:#81a1c1 fg:#ad5449"
format = '[$symbol$status]($style)'
# symbol = "quack"
disabled = false
not_found_symbol = "quack"
sigint_symbol = "int"
success_symbol = ""

[cmd_duration]
min_time = 1_000
format = '[$duration ]($style)'
